### ISSUE TITLE
Lilly's SERVIR to-do list

### ISSUE THREAD

**Issue by lillythomas** [developmentseed/sat-ml-training#19]
Last week we polished most of the pre-read content, namely the ML guide.

Remaining to-do items:

- [x] synthesize and clean up the deep learning crop type mapping code 
- [x] add remaining markdown instruction to the deep learning crop type mapping notebook
- [x] write out interim data from the deep learning crop type mapping notebook, so that we can jump steps if a student needs to.
- [x] write out a saved model from the deep learning crop type mapping notebook, so that we can jump steps if a student needs to.
- [x] implement notebook in google colab
- [x] send out pre-read materials to students
- [x] support development on remaining tutorial notebooks
